name: CI

on:
  pull_request:
    branches: [ "main", "staging" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - name: Instala Dependências usando Yarn
        run: yarn install --frozen-lockfile

      - name: Executa Testes
        run: npm run test:ci
